- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Uninstall nginx
      apt:
        name: nginx
        state: absent
    - name: Uninstall nginx configuration
      file:
        path: /etc/nginx/nginx.conf
        state: absent
